### ISSUE TITLE
Make it possible to disable write_external_storage permission

### ISSUE THREAD

**Issue by techee** [bitstadium/HockeySDK-Android#124]
On the page here:

http://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk

you describe that if one needs only crash reporting, the write_external_storage is not needed. However, because of manifest merging it gets always imported from

https://github.com/bitstadium/HockeySDK-Android/blob/develop/hockeysdk/src/main/AndroidManifest.xml

This permission requirement is quite unfortunate - it's part of "dangerous" permissions

http://developer.android.com/guide/topics/security/permissions.html

which at least on Android 6 trigger message saying something like "This app can access your files like photos..." which is quite an ugly user experience.

At the moment I use the "remove" conflict marker in my app's manifest to remove it from the manifest:

```
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:node="remove"/>
```

At least you should advice users to do the same. However, I'd suggest dropping WRITE_EXTERNAL_STORAGE unless absolutely necessary because then it seems the app reads/writes sensitive data on the disk.

**Comment by ranterle** [comment]
We do need `WRITE_EXTERNAL_STORAGE` for the in-app update process, otherwise the Android package installer can't access the downloaded APK.

I understand where you're coming from when only using HockeySDK for crash reporting or feedback but not for in-app updates. On this topic:

If you're building your app against Android 6.0 with `targetSdkVersion 23` this enables [runtime permissions](http://developer.android.com/training/permissions/requesting.html) - the permission is then only requested upon first use, e.g. when the user is using the in-app updater. You can also provide a rationale to the user why you need this permission e.g. as a reaction in an [`UpdateManagerListener`](https://github.com/bitstadium/HockeySDK-Android/blob/b6461b65dedc56b175fa72faefc1d147702e4ca8/hockeysdk/src/main/java/net/hockeyapp/android/UpdateManagerListener.java#L126).

If you absolutely can't target 23 and don't need the in-app updater, removing the permission through a `remove` marker in the manifest merging process is a viable workaround.

We are constantly improving the documentation as well as thinking about a more modular approach for the SDK. Thanks for pointing out this particular topic.

**Comment by techee** [comment]
@ranterle OK, thanks for the clarification. In any case I'd suggest updating the documentation (I guess it comes from the times when manifest merging didn't happen).

**Comment by ranterle** [comment]
Thanks @techee we'll be looking into this.

**Comment by blackjack75** [comment]
I would indeed put a big warning about this in the 3.7.0 upgrade notes.

We only use crash reporting (nothing else) and this bit us by surprise. A lot of users suddenly complained about the new permissions.

**Comment by TroubleMakerBen** [comment]
I just had a conversation on twitter about this. Maybe we find a workaround for this?
https://twitter.com/blackjack75/status/695064243968802817
https://twitter.com/blackjack75/status/695065087892180992
https://twitter.com/blackjack75/status/695065087892180992
https://twitter.com/blackjack75/status/695065761505763328
https://twitter.com/blackjack75/status/695065995820584961

**Comment by TroubleMakerBen** [comment]
@blackjack75 thanks for pointing this out to us! We'll look into this.

**Comment by ranterle** [comment]
We discussed this internally and are working on an overhaul of our documentation regarding this particular issue.
