### ISSUE TITLE
maxSdkVersion of WRITE_EXTERNAL_STORAGE permission gets overwritten

### ISSUE THREAD

**Issue by wlky** [bitstadium/HockeySDK-Android#327]
Hockeyapp sdk 5 sets maxSdkVersion of WRITE_EXTERNAL_STORAGE permission for the Project.

I just updated an app to Android 8 an in that process updated the hockeyapp sdk. This lead to a hell of a bug chase because suddenly part of the app, requiring a storage write permission, didn't work anymore.
Well hours later I now know it was not the android update but changes to the hockeyapp sdk, specifically this commit:
https://github.com/bitstadium/HockeySDK-Android/commit/8d24cc936fb5338d2c8d24f1e980bcd40a30b887
The permission in my apps' manifest looked like this:
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
This line turns into this one after building the apk:
`<uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        android:maxSdkVersion="18" />`
This resulted in the apps requests for write access to be categorically denied :P
The "solution" for me was to change my permission declaration to overwrite the maxsdkversion:
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="26" tools:replace="android:maxSdkVersion"/>`

**Comment by TroubleMakerBen** [comment]
Hey @wlky,
I‘m sorry you ran into issues when you updated the HockeySDK.

We have documented the required change about the permissions [release notes](https://github.com/bitstadium/HockeySDK-Android/releases/tag/5.0.0).
Have you missed the part there?
Or would you expect this to be documented elsewhere?
I‘d love to improve our documentation but am not sure where else to mention the change than in the release notes.

Is everything working for you if you redefine the permission as mentioned in the release notes?

Best,
Benjamin

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wlky** [comment]
Hi @TroubleMakerBen 
yeah sorry, I missed that..
Me personally I would have expected such an information in the Readme - together with the gradle compile line and the proguard information (if necessary). Just the basic stuff you need to add the library to a project.

**Comment by TroubleMakerBen** [comment]
Hi Yannik,

I'm glad you resolve the issue. Just as an FYI, [our knowledgebase](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk) contains all the information to integrate the SDK and mentions the permission in the "setup" step. Do you think this is visible enough?
I'm wondering if I can improve this and would welcome your input.

And thx a lot for using HockeyApp in the first place!

Benjamin

**Comment by MatkovIvan** [comment]
This issue is a duplicate of #301

**Comment by jamesdixon** [comment]
FWIW, this caused me TWO FULL DAYS of debugging. Holy hell. Please, please, please make this even more apparent. Yes, it's in the setup, but it's not something that jumps out at you.

In my case, my app was crashing every time a photo attempted to save on Android 6.

Again, please make this more apparent.

**Comment by jamesdixon** [comment]
@TroubleMakerBen actually, is there really a need to limit that permission in the first place? Given that you're giving people instructions on how to remove the limitation, I feel like it may be better left out rather than potentially cause major problems for people.

Speaking of problems, this was causing issues on Android 5/6, but not 7/8 and also not on every Android 5/6 phone. For those that may not be testing on tons of devices, this could cause major headaches when an app is released in the wild.

Again, I urge you to reconsider this if it isn't absolutely necessary.

**Comment by TroubleMakerBen** [comment]
Hi @jamesdixon,

I am very sorry for your 2 days of debugging hell... I've just added the release notes to every release since the 5.0 release and updated our KB. 

Now, talking about necessary, I hope that as soon as we bump the minSDK to 18 (which might or might not happen), I'm hoping to remove the limitation. The reason we added it is that we had quite a number of user feedback who were wondering about that "dangerous permission" for their app that they did not add.

Best,
Benjamin

**Comment by jamesdixon** [comment]
Benjamin,

No worries! It happens -- I just wanted to make sure it doesn't happen to others. Appreciate you updating the notes!

Sounds good regarding the SDK.

Keep up the good work on HockeyApp!

**Comment by TroubleMakerBen** [comment]
Thx for understanding. You're not the only person but it's not a very common issue (yet) – that said, the change has been out for several months now, so we'll see.

Also keep [AppCenter](https://www.hockeyapp.net/appcenter/about/) in mind for the future. Our the [App Center SDK](https://github.com/Microsoft/AppCenter-SDK-Apple) is on Github, too.

Have a nice day!

**Comment by jamesdixon** [comment]
No problem. Is HockeyApp going to be sunset in favor of App Center?

**Comment by TroubleMakerBen** [comment]
Hi @jamesdixon,

Yes, this will eventually happen. But don't worry, once the transition has been announced, you'll have another 12 months. Say, if we announce this in September 2018, you'll have until 2019 to make the move to App Center.

Best,
Benjamin
