### ISSUE TITLE
UDID mismatch between UpdateManager and the server causes the dialog not to prompt

### ISSUE THREAD

**Issue by XabierGoros** [bitstadium/HockeySDK-Android#350]
We're facing some issues to get to work the new version update check, and taking a look to the network requests the device does, it seems there's a udid mismatch betweeen what the SDK sends and what I have registered as a device in my account.

### My Account (registered devices)

``Android | 94641131b5YYYYYY |  SAMSUNG SM-G900V | 6.0.1 | Yes``

### SDK request at startup
https://sdk.hockeyapp.net/api/2/apps/XXXXMY_APP_IDXXXX?format=json&udid=bbb1cc8f-9314-446f-b100-XXXXXXXXXXXX&os=Android&os_version=6.0.1&device=SM-G900V&oem=samsung&app_version=50201200&sdk=HockeySDK&sdk_version=5.0.3&lang=es&usage_time=0

I don't know why the SDK sends the ``bbb1cc...`` udid instead of the registered one ``946411...`` That makes the backend to return an empty result ``[]`` and thus the dialog is not shown. If I manually change the ``udid`` parameter by the registered one ``94641131b5YYYYYY``, the server returns a proper result with all parameters the SDK needs to show the dialog.

I tried uninstalling and installing the APK through a web browser and even the HockeyApp app.

### Information
``Android HockeyAppSDK: 5.0.3``

**Comment by TroubleMakerBen** [comment]
Hey @XabierGoros,

What way of authentication are you using?
I'm not sure if this is related, but please note that from HockeySDK 5.0 and up, we don't support authentication by UDID anymore as ANDROID_ID (which was used before) can now change it's value (https://android-developers.googleblog.com/2017/04/changes-to-device-identifiers-in.html).

That said, would you please share your setup code with me? If you want to do so privately, please get in touch through [support](https://support.hockeyapp.net).

Best,
Benjamin

PS: You might also be interested in upgrading to HockeySDK-Android 5.1.0.

**Comment by jongarate** [comment]
Hi @TroubleMakerBen,

As a colleague of @XabierGoros I find myself in the necessity of stepping in. Having taken a look at the `HockeySDK-Android` source code and docs, I think we now have a more clear view of what's going on here.

We are currently not using any explicit authentication within the app, which I understand falls within the definiton of [Anonymous Authentication](https://support.hockeyapp.net/kb/client-integration-android/hockeyapp-for-android-sdk#4-5-1-anonymous). Up until **SDK 5.+** was introduced, `Secure.ANDROID_ID` was allowing us to identify users without asking them to formally provide credentials. This came in very handy since by the sole act of having `HockeyApp` installed on a tester's device (which is something we could consider accommodating within our release pipeline), allowed for closed release distributions without much fuss (because the user's device would be already associated just by login on it).

Fast forward to `HockeySDK-Android` **5.+** and, as I can see in the source, a random UUID is generated and stored locally per app. This results in the current situation being that users, despite being running Android pre-O devices, cannot be tracked to being on the same device as the one `HockeyApp` app notified (because UUID/UDIDs will _never_ match).

In this scenario, is formally asking the tester to provide **Hockey** credentials the only solution to track down users and deployment?

As a suggestion here, it would be nice if somehow the `HockeyApp` could be used as an authentication provider by allowing other apps to ask for some sort of token or uuid. This would reduce adoption friction with users who already have authorized credentials in a device.

Best regards,
Jon

**Comment by TroubleMakerBen** [comment]
Hey @jongarate,

You've summed up the whole issue really well and yes, right now, there is no way other than asking people for at least their email address of the HockeyApp account to get authentication working.

I'm creating an item on our backlog and forward your feature request to my PM. While we haven't heard any request for this last year, you're the second person this month asking for this. I'll update this issue once I know when we'll ship this. Thanks in advance for your understanding.

Best,
Benjamin

**Comment by natronite** [comment]
What's the status on this? This is driving me up a wall and I'm sure our clients don't appreciate not getting an update dialog at all.
