### ISSUE TITLE
Architectural question

### ISSUE THREAD

**Issue by sytolk** [bitstadium/HockeySDK-Android#367]
Why not simple generate Rest service clients for Android/iOS from swagger.json like this:
https://github.com/Panthro/hockeyapp-api-client

In this project swagger.yaml is manually written but swagger support can be provided from Rest service too:
https://swagger.io/getting-started/

b.t.w. Crash report is not send to Rest service with 5.1.0 version of the HockeySDK-Android. The last working version is 4.x

**Comment by TroubleMakerBen** [comment]
HI @sytolk,

We currently have no plans to provide generated REST service clients, e.g. using Swagger.

We currently are not aware of any issue with our API and sending crashes using the HockeySDK-Android. As this issue is pretty old, I'm closing this but if you continue to see any issues or have further questions, feel free to comment or reopen this issue.

Best,
Benjamin
