### ISSUE TITLE
Updating whilst pinned

### ISSUE THREAD

**Issue by Corical** [bitstadium/HockeySDK-Android#368]
Hi, I've been making use of HockeyApp for a while and it worked flawlessly. I've run into a problem now when my application is pinned, what can one do to alleviate the issue ?

It wouldn't launch the internal app manager to install, shows error of "unpinning isn't allowed". 

In your AsyncTask `DownloadFileTask` you have 
`intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);`. Removing it allows the manager to come up and install my update, but then after that my application is unpinned and not relaunched. Is there maybe another flag I need to set to have desired effect ?

HockeyApp version: 5.1.2
My main activity config:
-android:launchMode="singleTask"
-android:lockTaskMode="if_whitelisted"
Also setting my app as whitelisted through DPC.

Thanks,
C

**Comment by Corical** [comment]
After writing a test app and playing around, the only way I could make it work was to **not** set `FLAG_ACTIVITY_NEW_TASK` in `DownloadFileTask`, so that the installer still pops up after file downloaded. Then to get my app running after update, register `android.intent.action.MY_PACKAGE_REPLACED` receiver and start my main activity once it fires.

So to reiterate the environment my app runs in: 
- pinned
- set to home launcher
- runs in locktask mode (if_whitelist through DPC, I don't handle locktask explicitly in app)

If this is the case, it might be cool if you guys can give us an option so that the flag do not get set, or remove it entirely (not sure of implications). 

Thanks, 
C

**Comment by MatkovIvan** [comment]
Hi @Corical 

Thanks for getting in touch.
Unfortunately, as you noticed, the pinned applications are not currently supported.
We cannot just remove this flag since it is a breaking change. Also, introduce the new public option doesn't look as good idea to me. It is much better to check internally if the app is pinned.

We'll look at this in details, but I can't give you any ETA for this.
You can make a contribution if you want, it is always welcome :slightly_smiling_face:
I think the best choice for you now would be to use the modified version of SDK that you did during your tests.

Best,
Ivan
