### ISSUE TITLE
Question: Any way to manually log crashes/exceptions with HockeyApp SDK (without upgrading to newer AppCenter SDK)?

### ISSUE THREAD

**Issue by erawhctim** [bitstadium/HockeySDK-Android#415]
I know this functionality exists in the newer AppCenter SDK and `Crashes` API, but I'm trying to achieve the same functionality in our current build which doesn't include the new AppCenter SDK yet.

I'm not seeing a way to do this reading through the JavaDocs, am I missing something? Or does this require the AppCenter SDK?

**Comment by MatkovIvan** [comment]
Hi @erawhctim,

HockeyApp doesn't support handled exceptions reporting, but you can try to play with API that used to save uncaught ones.

https://github.com/bitstadium/HockeySDK-Android/blob/d8da029a1d86d207191c023617747f89e890dffc/hockeysdk/src/main/java/net/hockeyapp/android/ExceptionHandler.java#L43-L50

I'm going to close this issue since there is no official support for this.

Thanks,
Ivan

**Comment by erawhctim** [comment]
Thanks @MatkovIvan - I'll try that.
