### ISSUE TITLE
Crash Free Users % Per Day show n/a

### ISSUE THREAD

**Issue by zengcanxiang** [bitstadium/HockeySDK-Android#417]
We integrated hockey in both apps, but one didn't show Crash Free. How to set this in the background?

**Comment by Jamminroot** [comment]
Hey, @zengcanxiang, we're only using this repo for tracking issues related to SDK itself, while what you described looks more fitting for Intercom ticket support request.
You can create ticket through the portal ("Support" button on the bottom-right of the page).
And since it is not SDK issue, im closing this thread.
