### ISSUE TITLE
Handle OutOfMemoryError exceptions

### ISSUE THREAD

**Issue by RomainPiel** [bitstadium/HockeySDK-Android#74]
Pierre-Yves Ricau recently published a way to catch and handle OutOfMemoryError exceptions https://gist.github.com/pyricau/4726389fd64f3b7c6f32
I know these are tricky but could we consider adding a similar mechanism to catch and report OutOfMemoryError related crashes to HockeyApp?

**Comment by ranterle** [comment]
Hi Romain,
thanks for the suggestion. That sounds interesting from an SDK-user perspective. For the complete picture we will also have to upload the heap dump to HockeyApp in the process.
I'll look into this regarding both limitations in the backend as well as user experience, since heap dumps can be of substantial size, especially in the context of an OutOfMemoryError.

Best, Mat

**Comment by ranterle** [comment]
Closing this as there is no possible and user-friendly way of collecting and transmitting crash dump data for OOM exceptions. Transmitting those dumps would induce huge amounts of data use for your app's customers.
