### ISSUE TITLE
Support Runtime permissions

### ISSUE THREAD

**Issue by ranterle** [bitstadium/HockeySDK-Android#77]
Android M brings a new [runtime permissions model](http://developer.android.com/preview/features/runtime-permissions.html) which should also be supported prior to release of M.

**Comment by ranterle** [comment]
As listed in the [permissions best practices](http://developer.android.com/preview/features/runtime-permissions.html#best-practices) the permission `INTERNET` can be offered as a "normal permission", meaning if the developer adds it to the manifest, it will be automatically granted unless otherwise revoked by the user. (So runtime checks for said permission should still be in place)
That however is not true for `WRITE_EXTERNAL_STORAGE`.

**Comment by hzsweers** [comment]
Another thing to keep in mind with `WRITE_EXTERNAL_STORAGE` is that it was added in API 16, so I'm not even sure what you would do before that. Assume it's always available in <16 and otherwise call `ActivityCompat.checkSelfPermission(...)` in a method annotated with TargetApi(16).

FWIW I think the library should delegate permission handling to the app using it, and only do checks internally to see if the permission was granted.

**Comment by ranterle** [comment]
According to the docs `WRITE_EXTERNAL_STORAGE` was [added in API 4](http://developer.android.com/reference/android/Manifest.permission.html#WRITE_EXTERNAL_STORAGE).

It's not only a technical issue – we're looking for one that works in terms of user flow in-app but also SDK integration. And while more control over the permission granting process for the client app sounds good, that would also mean more work to integrate the SDK. We try to keep this as simple as possible.

**Comment by hzsweers** [comment]
Right, sorry I should be specified. Referencing it in
Manifest.permission.WRITE_EXTERNAL_STORAGE was oddly only added in 16, at
least when I tested it out recently.

Simple is definitely best, but when you consider requesting a permission
comes in the form of showing a UI, I think that should be completely
controlled by the app developers. Would be interesting to see what iOS
libraries do since they've had this for awhile.

**Comment by ranterle** [comment]
Both on iOS and on Android 6.0 (at least according to the article on runtime permissions) the system will take care of showing the dialog when you request permission(s).
* On iOS you provide a (mostly static/localized) string of why your app needs said permission, see [NSLocationWhenInUseUsageDescription](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW26) for example
* On Android 6.0 you can show a ["permission rationale"](https://developer.android.com/reference/android/app/Activity.html#shouldShowRequestPermissionRationale(java.lang.String)) prior to requesting the permission. That might be a point of handing control to the app, but apart from this the developer has no means to control the looks of the permission dialog.

**Comment by hzsweers** [comment]
Right, I just am saying that the actual request to show the dialog at all
should be controlled by the app, not the library. This way the developer
can control exactly when it's shown and ensure its contextually relevant to
whatever the user is doing at that point.

**Comment by ranterle** [comment]
Update or I didn't read carefully enough before: Normal permissions are granted at install time and you don't have to check for them at runtime anymore. See [here](https://developer.android.com/preview/features/runtime-permissions.html#normal)
So we can just leave `INTERNET` in the manifest and everything should be good.
Will focus on `WRITE_EXTERNAL_STORAGE` then.
Also referring to earlier comments: we can't use `ActivityCompat` since we won't include support-v4.
